### ISSUE TITLE
Mac OS 10.11 -bash: vagrant: command not found

### ISSUE THREAD

**Issue by lw2688** [dmc-2016/dmc#13]
after I installed successfully vagrant on mac, it shows -bash: vagrant: command not found...i figured out that this is due to the bug on mac, while i can't solve this problem after trying couple of solutions through terminal. Anybody have the same issue, please let me know

**Comment by mg3722** [comment]
I've also come across this problem

**Comment by lw2688** [comment]
ive already fix it...fortunately

**Comment by danilnagy** [comment]
Thanks lw2688, could you elaborate on your solution incase others are having a similar issue?

**Comment by lw2688** [comment]
Hi Professor Nagy，

For sure. I will upload my solutions ASAP..

Best，
Lei

**Comment by violetwhitney** [comment]
There are a number of things that can lead to the "-bash: vagrant: command not found" error. 

One possibility is that the PATH to Vagrant hasn't been set, and thus the shell language, Bash, doesn't understand Vagrant commands. Another possibility is that Vagrant wasn't installed properly at the PATH location, and another possibility is that the permissions are not allowed on the folder where BASH is installed. To check for these issues, assuming that you've already installed Vagrant, open a new terminal window, navigate to the appropriate folder, and type in 

vagrant up

again. Sometimes after installing new software you need a new terminal window for it to recognize the newly installed command.

If that doesn't work, run this command 

echo $PATH

![screen shot 2016-09-17 at 20 19 34](https://cloud.githubusercontent.com/assets/14256456/19118278/f1bf0ad8-8ae9-11e6-9aac-8752025806fd.png)

Then we can run some commands to list what files are in these PATH folders to make sure Vagrant is installed properly at these locations. You will then run the command "ls" and the path. It should look like this.

![image](https://cloud.githubusercontent.com/assets/14256456/19117923/b865e3ac-8ae8-11e6-9ac5-c9cff0758d4b.png)

You can see in this instance that there was a permissions issue. So we will run these commands to check what permissions we need to change.

ls -al /usr
ls -al /usr/local

![screen shot 2016-09-17 at 23 32 35](https://cloud.githubusercontent.com/assets/14256456/19118162/8b1ca236-8ae9-11e6-98ab-2c1b535354b3.png)

After the second output, the line with "bin" at the end indicates that the owner of the folder is a user named "502". That's no good. The "/usr/local" folder should be for the current user, i.e. you, and Mac OS shouldn't care.

Try this (adjusting for your user name and PATH):

sudo chown -R ourai /usr/local
sudo chmod 755 /usr/local/bin

The first command ensures that you're the owner of the /usr/local folder and all its contents. The second command changes the permissions on /usr/local/bin. You'll have to type your password after the first command.

Then in a new terminal window, let's check to see if the vagrant command is available:

ls -al /usr/local/bin
which vagrant

If you get some output like this, you should be good to go.
![screen shot 2016-09-17 at 11 45 48 pm](https://cloud.githubusercontent.com/assets/14256456/19118122/6b9fd81a-8ae9-11e6-96f2-1c620f0abe9e.png)

**Comment by danilnagy** [comment]
Great solution, Violet! I am closing this issue for now, if anyone encounters a similar error and none of Violet's suggestions work please post it here, and we can re-open the issue.
