### ISSUE TITLE
Stochastic Gradient Descent in case of multiple local minimums

### ISSUE THREAD

**Issue by mengchantang** [dmc-2016/dmc#62]
As I was reading the article it came to me that in some cases where multiple local minimums exist, how do we find out what combination of **W** and **b** lead to the global minimum?

**Comment by danilnagy** [comment]
@mengchantang This is a great theoretical question. The most accurate answer is that - as with all optimization approaches to complex multi-dimensional problems - we don't really know! The simple practical answer is that proper regularization usually helps us avoid this problem. The intuition is that the simpler the model, the more likely it will find the 'true', most simple solution - which usually corresponds to the global minimum.
