### ISSUE TITLE
Pull request not going through 

### ISSUE THREAD

**Issue by tolaoniyangi** [dmc-2016/dmc#65]
![screen shot 2016-10-05 at 6 20 17 pm](https://cloud.githubusercontent.com/assets/8798782/19133837/73573924-8b28-11e6-9a1c-9d16b743d5fb.png)

Trying to do a pull request/sync results in an Authentication Error - not sure what to do / how to get around this because I tried logging out and in again

**Comment by danilnagy** [comment]
@tolaoniyangi Sometimes this happens when you are not connected to the internet. I would just try again later and let me know if this is still happening.

**Comment by tolaoniyangi** [comment]
So I finally got this sorted out - turns out I had made a mistake in updating my local files so i was working in the local repo, and there were ssh connection issues that I was able to get around
