### ISSUE TITLE
"Vagrant Up" issue with exit code 1 (0x1)

### ISSUE THREAD

**Issue by MichaelPassion107** [dmc-2016/dmc#75]
![image 1](https://cloud.githubusercontent.com/assets/22333035/19218063/e06310ec-8dbc-11e6-889d-4c973a7cfe43.png)

I already enabled VT-x and restart my laptop, it will show up like this and remember nothing about what I did. Thank you for instructions!

**Comment by danilnagy** [comment]
Hi, have you tried searching for the error message in Google:

https://www.google.com/search?q=there+was+an+error+while+executing+vboxmanage&oq=there+was+an+error+while+executing+vboxmanage&aqs=chrome..69i57j0l3j69i60j69i61.4509j0j4&client=ms-android-att-us&sourceid=chrome-mobile&ie=UTF-8

And following some of the instructions there? I'm not personally familiar with this issue but if you still can't resolve it I can try to take a look 30 min before class this week.

**Comment by MichaelPassion107** [comment]
Hi professor,

My laptop keeps on messing up, which drives me crazy so that I just
reinstalled many times and it still doesn't work. I beg for
your instructions earlier than class, I will be there 30 minutes early.

Sincerely,
Mingze
