### ISSUE TITLE
Git Shell for Macs

### ISSUE THREAD

**Issue by dbm2135** [dmc-2016/dmc#8]
Hi Danil,
I've reached an impasse. I can't figure out how to how to open Git Shell from the GitHub desktop application. I'm on a Mac, and I don't have a setup icon in the top right corner. See photo. 
![screen shot 2016-09-12 at 4 34 32 pm](https://cloud.githubusercontent.com/assets/22079516/18451957/173ad106-7907-11e6-9a6d-4c5017c38ba5.png)

**Comment by dbm2135** [comment]
Thank you Violet for posting Mac instructions for the above issue! However when I try to run
 "git remote add upstream https://github.com/dmc-2016/dmc.git" I get the following result:
The program 'git' is currently not installed. To run 'git' please ask your administrator to install the package 'git'
It said earlier in the instructions that Mac users don't need to install Git. Is there a different command we can use instead?

Thanks

**Comment by dbm2135** [comment]
It turns out that I didn't have the proper command line developer tools on my Mac to run Git, so I had to download software from the Apple developer website to run it (www.developer.apple.com). Specifically I downloaded Command Line Tools for OS X 10.11. After that, I was able to successfully complete the assignment.

**Comment by danilnagy** [comment]
Good find dbm2135! Violet and I must have both had command line tools already installed. I will make sure to update the instructions.
